config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :appointments 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  validates :name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
  end

  def index
    @appointments = Appointment.all
  end

  def create
    @appointment = Appointment.new(appointment_params)

    @appointment.save
    redirect_to @appointment
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

 private
   def appointment_params
     params.require(:appointment).permit(:name)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<%= link_to 'Create appointments', new_appointment_path %><br>

<table>
  <tr>
    <th>Name</th>
  </tr>

  <%= @appointments.each do |appointment| %>
    <tr>
      <td> <%= appointment.name %> </td>
      <td> <%= link_to 'Show', appointment_path(appointment) %> </td>
      <td> <%= link_to 'Destroy', appointment_path(appointment), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
    </tr>
  <% end %>
</table>

app/views/appointments/invoice.html.erb
<p>
  <strong>Name:</strong>
  <%= @appointment.balance %>
</p>

app/views/appointments/new.html.erb
<h1>New article.</h1>

<%= form_for :appointment, url: appointments_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<h1>Invoice</h1>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>
<p>
  <strong>Payable:</strong>
  <%= @appointment.balance %>
</p>

<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clinic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>